<?php

namespace Database\Seeders;

use App\Models\Cours;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CoursSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cours = [

            /*SEMESTRE 1*/

            /*IG1-A*/
            [
                'classe_id' => 1,
                'semestre' => 1,
                'ue_id' => 1,
                'credit' => 6,
                'ecue1' => 1,
                // 'enseignant1' => 1,
                'heure_theorique1' => 30,
                'ecue2' => 2,
                // 'enseignant2' => 2,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 1,
                'semestre' => 1,
                'ue_id' => 2,
                'credit' => 6,
                'ecue1' => 3,
                // 'enseignant1' => 3,
                'heure_theorique1' => 30,
                'ecue2' => 4,
                // 'enseignant2' => 4,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 1,
                'semestre' => 1,
                'ue_id' => 3,
                'credit' => 4,
                'ecue1' => 5,
                // 'enseignant1' => 5,
                'heure_theorique1' => 20,
                'ecue2' => 6,
                // 'enseignant2' => 6,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 1,
                'semestre' => 1,
                'ue_id' => 4,
                'credit' => 4,
                'ecue1' => 7,
                // 'enseignant1' => 7,
                'heure_theorique1' => 10,
                'ecue2' => 8,
                // 'enseignant2' => 8,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 1,
                'semestre' => 1,
                'ue_id' => 5,
                'credit' => 4,
                'ecue1' => 9,
                // 'enseignant1' => 9,
                'heure_theorique1' => 40,
                'ecue2' => null,
                // 'enseignant2' => 10,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 1,
                'semestre' => 1,
                'ue_id' => 6,
                'credit' => 3,
                'ecue1' => 10,
                // 'enseignant1' => 11,
                'heure_theorique1' => 15,
                'ecue2' => null,
                // 'enseignant2' => 12,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 1,
                'semestre' => 1,
                'ue_id' => 7,
                'credit' => 2,
                'ecue1' => 11,
                // 'enseignant1' => 13,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 14,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 1,
                'semestre' => 1,
                'ue_id' => 8,
                'credit' => 1,
                'ecue1' => 12,
                // 'enseignant1' => 15,
                'heure_theorique1' => 10,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],


            /*IG1-B*/
            [
                'classe_id' => 2,
                'semestre' => 1,
                'ue_id' => 1,
                'credit' => 6,
                'ecue1' => 1,
                // 'enseignant1' => 1,
                'heure_theorique1' => 30,
                'ecue2' => 2,
                // 'enseignant2' => 2,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 2,
                'semestre' => 1,
                'ue_id' => 2,
                'credit' => 6,
                'ecue1' => 3,
                // 'enseignant1' => 3,
                'heure_theorique1' => 30,
                'ecue2' => 4,
                // 'enseignant2' => 4,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 2,
                'semestre' => 1,
                'ue_id' => 3,
                'credit' => 4,
                'ecue1' => 5,
                // 'enseignant1' => 5,
                'heure_theorique1' => 20,
                'ecue2' => 6,
                // 'enseignant2' => 6,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 2,
                'semestre' => 1,
                'ue_id' => 4,
                'credit' => 4,
                'ecue1' => 7,
                // 'enseignant1' => 7,
                'heure_theorique1' => 10,
                'ecue2' => 8,
                // 'enseignant2' => 8,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 2,
                'semestre' => 1,
                'ue_id' => 5,
                'credit' => 4,
                'ecue1' => 9,
                // 'enseignant1' => 9,
                'heure_theorique1' => 40,
                'ecue2' => null,
                // 'enseignant2' => 10,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 2,
                'semestre' => 1,
                'ue_id' => 6,
                'credit' => 3,
                'ecue1' => 10,
                // 'enseignant1' => 11,
                'heure_theorique1' => 15,
                'ecue2' => null,
                // 'enseignant2' => 12,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 2,
                'semestre' => 1,
                'ue_id' => 7,
                'credit' => 2,
                'ecue1' => 11,
                // 'enseignant1' => 13,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 14,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 2,
                'semestre' => 1,
                'ue_id' => 8,
                'credit' => 1,
                'ecue1' => 12,
                // 'enseignant1' => 15,
                'heure_theorique1' => 10,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],


            /*SEMESTRE 2*/

            /*IG1-A*/

            [
                'classe_id' => 1,
                'semestre' => 2,
                'ue_id' => 9,
                'credit' => 6,
                'ecue1' => 13,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => 14,
                // 'enseignant2' => 16,
                'heure_theorique2' => 40,
            ],
            [
                'classe_id' => 1,
                'semestre' => 2,
                'ue_id' => 10,
                'credit' => 6,
                'ecue1' => 15,
                // 'enseignant1' => 15,
                'heure_theorique1' => 40,
                'ecue2' => 16,
                // 'enseignant2' => 16,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 1,
                'semestre' => 2,
                'ue_id' => 11,
                'credit' => 4,
                'ecue1' => 17,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => 18,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 1,
                'semestre' => 2,
                'ue_id' => 12,
                'credit' => 4,
                'ecue1' => 19,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => 20,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 1,
                'semestre' => 2,
                'ue_id' => 13,
                'credit' => 3,
                'ecue1' => 21,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 1,
                'semestre' => 2,
                'ue_id' => 14,
                'credit' => 3,
                'ecue1' => 22,
                // 'enseignant1' => 15,
                'heure_theorique1' => 15,
                'ecue2' => 23,
                // 'enseignant2' => 16,
                'heure_theorique2' => 15,
            ],
            [
                'classe_id' => 1,
                'semestre' => 2,
                'ue_id' => 15,
                'credit' => 3,
                'ecue1' => 24,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 1,
                'semestre' => 2,
                'ue_id' => 16,
                'credit' => 1,
                'ecue1' => 25,
                // 'enseignant1' => 15,
                'heure_theorique1' => 0,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],

            /*IG1-B*/

            [
                'classe_id' => 2,
                'semestre' => 2,
                'ue_id' => 9,
                'credit' => 6,
                'ecue1' => 13,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => 14,
                // 'enseignant2' => 16,
                'heure_theorique2' => 40,
            ],
            [
                'classe_id' => 2,
                'semestre' => 2,
                'ue_id' => 10,
                'credit' => 6,
                'ecue1' => 15,
                // 'enseignant1' => 15,
                'heure_theorique1' => 40,
                'ecue2' => 16,
                // 'enseignant2' => 16,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 2,
                'semestre' => 2,
                'ue_id' => 11,
                'credit' => 4,
                'ecue1' => 17,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => 18,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 2,
                'semestre' => 2,
                'ue_id' => 12,
                'credit' => 4,
                'ecue1' => 19,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => 20,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 2,
                'semestre' => 2,
                'ue_id' => 13,
                'credit' => 3,
                'ecue1' => 21,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 2,
                'semestre' => 2,
                'ue_id' => 14,
                'credit' => 3,
                'ecue1' => 22,
                // 'enseignant1' => 15,
                'heure_theorique1' => 15,
                'ecue2' => 23,
                // 'enseignant2' => 16,
                'heure_theorique2' => 15,
            ],
            [
                'classe_id' => 2,
                'semestre' => 2,
                'ue_id' => 15,
                'credit' => 3,
                'ecue1' => 24,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 2,
                'semestre' => 2,
                'ue_id' => 16,
                'credit' => 1,
                'ecue1' => 25,
                // 'enseignant1' => 15,
                'heure_theorique1' => 0,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],

            /*SEMESTRE 3*/

            /*IG2-A*/

            [
                'classe_id' => 3,
                'semestre' => 3,
                'ue_id' => 17,
                'credit' => 5,
                'ecue1' => 26,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => 27,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 3,
                'semestre' => 3,
                'ue_id' => 18,
                'credit' => 5,
                'ecue1' => 28,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => 29,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 3,
                'semestre' => 3,
                'ue_id' => 19,
                'credit' => 5,
                'ecue1' => 30,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => 31,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 3,
                'semestre' => 3,
                'ue_id' => 20,
                'credit' => 4,
                'ecue1' => 32,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => 33,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 3,
                'semestre' => 3,
                'ue_id' => 21,
                'credit' => 3,
                'ecue1' => 34,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 3,
                'semestre' => 3,
                'ue_id' => 22,
                'credit' => 2,
                'ecue1' => 35,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 3,
                'semestre' => 3,
                'ue_id' => 23,
                'credit' => 4,
                'ecue1' => 36,
                // 'enseignant1' => 15,
                'heure_theorique1' => 40,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 3,
                'semestre' => 3,
                'ue_id' => 24,
                'credit' => 2,
                'ecue1' => 37,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],

            /*IG2-B*/

            [
                'classe_id' => 4,
                'semestre' => 3,
                'ue_id' => 17,
                'credit' => 5,
                'ecue1' => 26,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => 27,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 4,
                'semestre' => 3,
                'ue_id' => 18,
                'credit' => 5,
                'ecue1' => 28,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => 29,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 4,
                'semestre' => 3,
                'ue_id' => 19,
                'credit' => 5,
                'ecue1' => 30,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => 31,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 4,
                'semestre' => 3,
                'ue_id' => 20,
                'credit' => 4,
                'ecue1' => 32,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => 33,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 4,
                'semestre' => 3,
                'ue_id' => 21,
                'credit' => 3,
                'ecue1' => 34,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 4,
                'semestre' => 3,
                'ue_id' => 22,
                'credit' => 2,
                'ecue1' => 35,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 4,
                'semestre' => 3,
                'ue_id' => 23,
                'credit' => 4,
                'ecue1' => 36,
                // 'enseignant1' => 15,
                'heure_theorique1' => 40,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 4,
                'semestre' => 3,
                'ue_id' => 24,
                'credit' => 2,
                'ecue1' => 37,
                // 'enseignant1' => 15,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 16,
                'heure_theorique2' => null,
            ],

            /*SEMESTRE 4*/

            /*IG2-A*/

            [
                'classe_id' => 3,
                'semestre' => 4,
                'ue_id' => 25,
                'credit' => 5,
                'ecue1' => 38,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => 39,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 3,
                'semestre' => 4,
                'ue_id' => 26,
                'credit' => 4,
                'ecue1' => 40,
                // 'enseignant1' => 17,
                'heure_theorique1' => 20,
                'ecue2' => 41,
                // 'enseignant2' => 18,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 3,
                'semestre' => 4,
                'ue_id' => 27,
                'credit' => 4,
                'ecue1' => 42,
                // 'enseignant1' => 19,
                'heure_theorique1' => 40,
                'ecue2' => null,
                // 'enseignant2' => 20,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 3,
                'semestre' => 4,
                'ue_id' => 28,
                'credit' => 5,
                'ecue1' => 43,
                // 'enseignant1' => 21,
                'heure_theorique1' => 30,
                'ecue2' => 44,
                // 'enseignant2' => 22,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 3,
                'semestre' => 4,
                'ue_id' => 29,
                'credit' => 5,
                'ecue1' => 45,
                // 'enseignant1' => 23,
                'heure_theorique1' => null,
                'ecue2' => null,
                // 'enseignant2' => 24,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 3,
                'semestre' => 4,
                'ue_id' => 30,
                'credit' => 3,
                'ecue1' => 46,
                // 'enseignant1' => 25,
                'heure_theorique1' => 15,
                'ecue2' => 47,
                // 'enseignant2' => 26,
                'heure_theorique2' => 15,
            ],
            [
                'classe_id' => 3,
                'semestre' => 4,
                'ue_id' => 31,
                'credit' => 3,
                'ecue1' => 48,
                // 'enseignant1' => 27,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 28,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 3,
                'semestre' => 4,
                'ue_id' => 32,
                'credit' => 1,
                'ecue1' => 49,
                // 'enseignant1' => 29,
                'heure_theorique1' => 0,
                'ecue2' => null,
                // 'enseignant2' => 30,
                'heure_theorique2' => null,
            ],

            /*IG2-B*/

            [
                'classe_id' => 4,
                'semestre' => 4,
                'ue_id' => 25,
                'credit' => 5,
                'ecue1' => 38,
                // 'enseignant1' => 15,
                'heure_theorique1' => 30,
                'ecue2' => 39,
                // 'enseignant2' => 16,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 4,
                'semestre' => 4,
                'ue_id' => 26,
                'credit' => 4,
                'ecue1' => 40,
                // 'enseignant1' => 17,
                'heure_theorique1' => 20,
                'ecue2' => 41,
                // 'enseignant2' => 18,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 4,
                'semestre' => 4,
                'ue_id' => 27,
                'credit' => 4,
                'ecue1' => 42,
                // 'enseignant1' => 19,
                'heure_theorique1' => 40,
                'ecue2' => null,
                // 'enseignant2' => 20,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 4,
                'semestre' => 4,
                'ue_id' => 28,
                'credit' => 5,
                'ecue1' => 43,
                // 'enseignant1' => 21,
                'heure_theorique1' => 30,
                'ecue2' => 44,
                // 'enseignant2' => 22,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 4,
                'semestre' => 4,
                'ue_id' => 29,
                'credit' => 5,
                'ecue1' => 45,
                // 'enseignant1' => 23,
                'heure_theorique1' => null,
                'ecue2' => null,
                // 'enseignant2' => 24,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 4,
                'semestre' => 4,
                'ue_id' => 30,
                'credit' => 3,
                'ecue1' => 46,
                // 'enseignant1' => 25,
                'heure_theorique1' => 15,
                'ecue2' => 47,
                // 'enseignant2' => 26,
                'heure_theorique2' => 15,
            ],
            [
                'classe_id' => 4,
                'semestre' => 4,
                'ue_id' => 31,
                'credit' => 3,
                'ecue1' => 48,
                // 'enseignant1' => 27,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 28,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 4,
                'semestre' => 4,
                'ue_id' => 32,
                'credit' => 1,
                'ecue1' => 49,
                // 'enseignant1' => 29,
                'heure_theorique1' => 0,
                'ecue2' => null,
                // 'enseignant2' => 30,
                'heure_theorique2' => null,
            ],


            /*SEMESTRE 5*/

            /*AIP*/

            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 33,
                'credit' => 4,
                'ecue1' => 50,
                // 'enseignant1' => 29,
                'heure_theorique1' => 20,
                'ecue2' => 51,
                // 'enseignant2' => 30,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 34,
                'credit' => 3,
                'ecue1' => 52,
                // 'enseignant1' => 31,
                'heure_theorique1' => 20,
                'ecue2' => 53,
                // 'enseignant2' => 32,
                'heure_theorique2' => 10,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 35,
                'credit' => 4,
                'ecue1' => 54,
                // 'enseignant1' => 33,
                'heure_theorique1' => 20,
                'ecue2' => 55,
                // 'enseignant2' => 34,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 36,
                'credit' => 5,
                'ecue1' => 56,
                // 'enseignant1' => 35,
                'heure_theorique1' => 30,
                'ecue2' => 57,
                // 'enseignant2' => 36,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 37,
                'credit' => 3,
                'ecue1' => 58,
                // 'enseignant1' => 37,
                'heure_theorique1' => 20,
                'ecue2' => 59,
                // 'enseignant2' => 38,
                'heure_theorique2' => 10,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 38,
                'credit' => 2,
                'ecue1' => 60,
                // 'enseignant1' => 39,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 40,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 39,
                'credit' => 2,
                'ecue1' => 61,
                // 'enseignant1' => 41,
                'heure_theorique1' => 10,
                'ecue2' => 62,
                // 'enseignant2' => 42,
                'heure_theorique2' => 10,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 40,
                'credit' => 3,
                'ecue1' => 63,
                // 'enseignant1' => 43,
                'heure_theorique1' => 20,
                'ecue2' => 64,
                // 'enseignant2' => 44,
                'heure_theorique2' => 10,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 41,
                'credit' => 1,
                'ecue1' => 65,
                // 'enseignant1' => 45,
                'heure_theorique1' => 10,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 5,
                'semestre' => 5,
                'ue_id' => 42,
                'credit' => 3,
                'ecue1' => 66,
                // 'enseignant1' => 45,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],

            /*ARI*/

            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 43,
                'credit' => 4,
                'ecue1' => 67,
                // 'enseignant1' => 29,
                'heure_theorique1' => 20,
                'ecue2' => 68,
                // 'enseignant2' => 30,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 44,
                'credit' => 4,
                'ecue1' => 69,
                // 'enseignant1' => 31,
                'heure_theorique1' => 20,
                'ecue2' => 70,
                // 'enseignant2' => 32,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 45,
                'credit' => 3,
                'ecue1' => 71,
                // 'enseignant1' => 33,
                'heure_theorique1' => 20,
                'ecue2' => 72,
                // 'enseignant2' => 34,
                'heure_theorique2' => 10,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 46,
                'credit' => 5,
                'ecue1' => 73,
                // 'enseignant1' => 33,
                'heure_theorique1' => 20,
                'ecue2' => 74,
                // 'enseignant2' => 34,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 47,
                'credit' => 3,
                'ecue1' => 75,
                // 'enseignant1' => 33,
                'heure_theorique1' => 20,
                'ecue2' => 76,
                // 'enseignant2' => 34,
                'heure_theorique2' => 10,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 48,
                'credit' => 2,
                'ecue1' => 77,
                // 'enseignant1' => 39,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 40,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 49,
                'credit' => 2,
                'ecue1' => 78,
                // 'enseignant1' => 41,
                'heure_theorique1' => 10,
                'ecue2' => 79,
                // 'enseignant2' => 42,
                'heure_theorique2' => 10,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 50,
                'credit' => 3,
                'ecue1' => 80,
                // 'enseignant1' => 43,
                'heure_theorique1' => 20,
                'ecue2' => 81,
                // 'enseignant2' => 44,
                'heure_theorique2' => 10,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 51,
                'credit' => 1,
                'ecue1' => 82,
                // 'enseignant1' => 45,
                'heure_theorique1' => 10,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 6,
                'semestre' => 5,
                'ue_id' => 52,
                'credit' => 3,
                'ecue1' => 83,
                // 'enseignant1' => 45,
                'heure_theorique1' => 30,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],

            /*SEMESTRE 6*/

            /*AIP*/

            [
                'classe_id' => 5,
                'semestre' => 6,
                'ue_id' => 53,
                'credit' => 4,
                'ecue1' => 84,
                // 'enseignant1' => 45,
                'heure_theorique1' => 20,
                'ecue2' => 85,
                // 'enseignant2' => 46,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 5,
                'semestre' => 6,
                'ue_id' => 54,
                'credit' => 5,
                'ecue1' => 86,
                // 'enseignant1' => 45,
                'heure_theorique1' => 20,
                'ecue2' => 87,
                // 'enseignant2' => 46,
                'heure_theorique2' => 30,
            ],
            [
                'classe_id' => 5,
                'semestre' => 6,
                'ue_id' => 55,
                'credit' => 18,
                'ecue1' => 88,
                // 'enseignant1' => 45,
                'heure_theorique1' => 0,
                'ecue2' => 89,
                // 'enseignant2' => 46,
                'heure_theorique2' => 0,
            ],
            [
                'classe_id' => 5,
                'semestre' => 6,
                'ue_id' => 56,
                'credit' => 2,
                'ecue1' => 90,
                // 'enseignant1' => 45,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 5,
                'semestre' => 6,
                'ue_id' => 57,
                'credit' => 1,
                'ecue1' => 91,
                // 'enseignant1' => 45,
                'heure_theorique1' => 0,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],

            /*ARI*/

            [
                'classe_id' => 6,
                'semestre' => 6,
                'ue_id' => 58,
                'credit' => 3,
                'ecue1' => 92,
                // 'enseignant1' => 45,
                'heure_theorique1' => 15,
                'ecue2' => 93,
                // 'enseignant2' => 46,
                'heure_theorique2' => 15,
            ],
            [
                'classe_id' => 6,
                'semestre' => 6,
                'ue_id' => 59,
                'credit' => 4,
                'ecue1' => 94,
                // 'enseignant1' => 45,
                'heure_theorique1' => 20,
                'ecue2' => 95,
                // 'enseignant2' => 46,
                'heure_theorique2' => 20,
            ],
            [
                'classe_id' => 6,
                'semestre' => 6,
                'ue_id' => 60,
                'credit' => 2,
                'ecue1' => 96,
                // 'enseignant1' => 45,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 6,
                'semestre' => 6,
                'ue_id' => 61,
                'credit' => 18,
                'ecue1' => 97,
                // 'enseignant1' => 45,
                'heure_theorique1' => 0,
                'ecue2' => 98,
                // 'enseignant2' => 46,
                'heure_theorique2' => 0,
            ],
            [
                'classe_id' => 6,
                'semestre' => 6,
                'ue_id' => 62,
                'credit' => 2,
                'ecue1' => 99,
                // 'enseignant1' => 45,
                'heure_theorique1' => 20,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],
            [
                'classe_id' => 6,
                'semestre' => 6,
                'ue_id' => 63,
                'credit' => 1,
                'ecue1' => 100,
                // 'enseignant1' => 45,
                'heure_theorique1' => 0,
                'ecue2' => null,
                // 'enseignant2' => 46,
                'heure_theorique2' => null,
            ],





        ];
        foreach ($cours as $cour) {

            Cours::create([
                'classe_id' => $cour['classe_id'],
                'semestre' => $cour['semestre'],
                'ue_id' => $cour['ue_id'],
                'credit' => $cour['credit'],
                'ecue1' => $cour['ecue1'],
                // 'enseignant1' => $cour['enseignant1'],
                'heure_theorique1' => $cour['heure_theorique1'],
                'ecue2' => $cour['ecue2'],
                // 'enseignant2' => $cour['enseignant2'],
                'heure_theorique2' => $cour['heure_theorique2'],
            ]);
        }
    }
}
